# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Wed Sep 10 00:02:21 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(601, 81)
        self.groupBox_11 = QtGui.QGroupBox(Form)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 0, 601, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.groupBox_11.setPalette(palette)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_11)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 581, 21))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.rb_no_headerTail = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.rb_no_headerTail.setObjectName(_fromUtf8("rb_no_headerTail"))
        self.horizontalLayout_18.addWidget(self.rb_no_headerTail)
        self.rb_cr = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.rb_cr.setObjectName(_fromUtf8("rb_cr"))
        self.horizontalLayout_18.addWidget(self.rb_cr)
        self.rb_lf = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.rb_lf.setObjectName(_fromUtf8("rb_lf"))
        self.horizontalLayout_18.addWidget(self.rb_lf)
        self.rb_crlf = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.rb_crlf.setObjectName(_fromUtf8("rb_crlf"))
        self.horizontalLayout_18.addWidget(self.rb_crlf)
        self.rb_stx_etx_crlf = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.rb_stx_etx_crlf.setObjectName(_fromUtf8("rb_stx_etx_crlf"))
        self.horizontalLayout_18.addWidget(self.rb_stx_etx_crlf)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_11)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 581, 22))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.cb_hex_ascii = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.cb_hex_ascii.setMinimumSize(QtCore.QSize(5, 0))
        self.cb_hex_ascii.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_hex_ascii.setObjectName(_fromUtf8("cb_hex_ascii"))
        self.cb_hex_ascii.addItem(_fromUtf8(""))
        self.cb_hex_ascii.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.cb_hex_ascii)
        self.le_header_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.le_header_1.setMaximumSize(QtCore.QSize(45, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.le_header_1.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(False)
        self.le_header_1.setFont(font)
        self.le_header_1.setToolTip(_fromUtf8(""))
        self.le_header_1.setAutoFillBackground(True)
        self.le_header_1.setText(_fromUtf8(""))
        self.le_header_1.setObjectName(_fromUtf8("le_header_1"))
        self.horizontalLayout_19.addWidget(self.le_header_1)
        self.le_header_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.le_header_2.setMaximumSize(QtCore.QSize(45, 16777215))
        self.le_header_2.setObjectName(_fromUtf8("le_header_2"))
        self.horizontalLayout_19.addWidget(self.le_header_2)
        self.le_data = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.le_data.setMinimumSize(QtCore.QSize(244, 0))
        self.le_data.setMaximumSize(QtCore.QSize(312, 16777215))
        self.le_data.setObjectName(_fromUtf8("le_data"))
        self.horizontalLayout_19.addWidget(self.le_data)
        self.le_tail_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_tail_1.sizePolicy().hasHeightForWidth())
        self.le_tail_1.setSizePolicy(sizePolicy)
        self.le_tail_1.setMaximumSize(QtCore.QSize(45, 16777215))
        self.le_tail_1.setObjectName(_fromUtf8("le_tail_1"))
        self.horizontalLayout_19.addWidget(self.le_tail_1)
        self.le_tail_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.le_tail_2.setMaximumSize(QtCore.QSize(45, 16777215))
        self.le_tail_2.setObjectName(_fromUtf8("le_tail_2"))
        self.horizontalLayout_19.addWidget(self.le_tail_2)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.rb_no_headerTail, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.slot_no_item)
        QtCore.QObject.connect(self.rb_cr, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.slot_cr)
        QtCore.QObject.connect(self.rb_lf, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.slot_lf)
        QtCore.QObject.connect(self.rb_crlf, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.slot_crlf)
        QtCore.QObject.connect(self.rb_stx_etx_crlf, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.slot_stx_etx_crlf)
        QtCore.QObject.connect(self.cb_hex_ascii, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.slot_hex_or_ascii)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_11.setTitle(_translate("Form", "프로토콜", None))
        self.rb_no_headerTail.setText(_translate("Form", "없음", None))
        self.rb_cr.setText(_translate("Form", "CR (0x0D)", None))
        self.rb_lf.setText(_translate("Form", "LF (0x0A)", None))
        self.rb_crlf.setText(_translate("Form", "CR + LF (0x0D + 0x0A)", None))
        self.rb_stx_etx_crlf.setText(_translate("Form", "STX + ETX + CRLF(0x02, 0x03)", None))
        self.cb_hex_ascii.setItemText(0, _translate("Form", "HEX", None))
        self.cb_hex_ascii.setItemText(1, _translate("Form", "ASCII", None))

